name 'hitch'
maintainer 'Guido Schöning'
maintainer_email 'guido.schoening@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures hitch'
long_description 'Installs/Configures hitch'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'ubuntu'
issues_url 'https://github.com/goblin23/hitch/issues'
source_url 'https://github.com/goblin23/hitch'
